#!/usr/bin/env bash
#
# Publish the gallery to a local clone of clawpack.github.com.
#
# The gallery is built by hand and is not part of the CI publish pipeline: its
# gallery_*.rst pages and thumbnails are generated by gallery/gallery/gallery.py,
# which first has to run the Clawpack and PyClaw examples (see gallery/README.md).
# So this stays a manual step.
#
# Set DRYRUN=1 to see what would be copied without writing anything.
#
# Additive on purpose: no --delete.  See the note in rsync_doc.sh.

set -euo pipefail

SRC=gallery/_build/html
DEST=../clawpack.github.com/gallery

if [ ! -f "$SRC/index.html" ]; then
    echo "error: no gallery build found at $SRC/index.html" >&2
    echo "       run 'cd gallery && make html' first (see gallery/README.md)" >&2
    exit 1
fi

if [ ! -d "$DEST" ]; then
    echo "error: $DEST does not exist" >&2
    echo "       clone clawpack/clawpack.github.com next to this repo" >&2
    exit 1
fi

rsync -av ${DRYRUN:+--dry-run} "$SRC"/ "$DEST"/
