.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. clawpack stuff
.. _Clawpack GitHub: https://github.com/orgs/clawpack

.. other stuff
.. _python: http://www.python.org

.. |emdash| unicode:: U+02014

.. vim: ft=rst
